# Generated by Django 3.2.16 on 2022-12-15 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('vendido_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
