# Generated by Django 4.1.4 on 2022-12-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_ventas_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='precio_total',
            new_name='costo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad_total',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='precio_unitario',
        ),
    ]
